import { describe, expect, it } from 'vitest';
import type { University } from '@/types/university';
import { runFuzzySearch } from './fuzzy-search';

const baseUniversities: University[] = [
  {
    id: 1,
    vari: 'Valkoinen',
    variLabel: 'Valkoinen',
    variBase: ['valkoinen'],
    hex: '#fff',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Valkoinen',
    slug: 'org-valkoinen',
    oppilaitos: 'Koulu',
  },
  {
    id: 2,
    vari: 'Musta',
    variLabel: 'Musta',
    variBase: ['musta'],
    hex: '#000',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Musta',
    slug: 'org-musta',
    oppilaitos: 'Koulu',
  },
  {
    id: 3,
    vari: 'Punainen',
    variLabel: 'Punainen',
    variBase: ['punainen'],
    hex: '#f00',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Punainen',
    slug: 'org-punainen',
    oppilaitos: 'Koulu',
  },
  {
    id: 4,
    vari: 'Sininen',
    variLabel: 'Sininen',
    variBase: ['sininen'],
    hex: '#00f',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Sininen',
    slug: 'org-sininen',
    oppilaitos: 'Koulu',
  },
  {
    id: 5,
    vari: 'Vihreä',
    variLabel: 'Vihreä',
    variBase: ['vihreä'],
    hex: '#0f0',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Vihrea',
    slug: 'org-vihrea',
    oppilaitos: 'Koulu',
  },
  {
    id: 6,
    vari: 'Keltainen',
    variLabel: 'Keltainen',
    variBase: ['keltainen'],
    hex: '#ff0',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Keltainen',
    slug: 'org-keltainen',
    oppilaitos: 'Koulu',
  },
  {
    id: 7,
    vari: 'Oranssi',
    variLabel: 'Oranssi',
    variBase: ['oranssi'],
    hex: '#fa0',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Oranssi',
    slug: 'org-oranssi',
    oppilaitos: 'Koulu',
  },
  {
    id: 8,
    vari: 'Violetti',
    variLabel: 'Violetti',
    variBase: ['violetti'],
    hex: '#70f',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Violetti',
    slug: 'org-violetti',
    oppilaitos: 'Koulu',
  },
  {
    id: 9,
    vari: 'Pinkki',
    variLabel: 'Pinkki',
    variBase: ['pinkki'],
    hex: '#f8c',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Pinkki',
    slug: 'org-pinkki',
    oppilaitos: 'Koulu',
  },
  {
    id: 10,
    vari: 'Harmaa',
    variLabel: 'Harmaa',
    variBase: ['harmaa'],
    hex: '#999',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Harmaa',
    slug: 'org-harmaa',
    oppilaitos: 'Koulu',
  },
  {
    id: 11,
    vari: 'Ruskea',
    variLabel: 'Ruskea',
    variBase: ['ruskea'],
    hex: '#741',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Ruskea',
    slug: 'org-ruskea',
    oppilaitos: 'Koulu',
  },
  {
    id: 12,
    vari: 'Turkoosi',
    variLabel: 'Turkoosi',
    variBase: ['turkoosi'],
    hex: '#0cc',
    alue: 'A',
    ala: 'X',
    ainejarjesto: 'Org Turkoosi',
    slug: 'org-turkoosi',
    oppilaitos: 'Koulu',
  },
];

const cases: Array<{ query: string; expectedId: number }> = [
  { query: 'valkoiset', expectedId: 1 },
  { query: 'mustat', expectedId: 2 },
  { query: 'punaiset', expectedId: 3 },
  { query: 'siniset', expectedId: 4 },
  { query: 'vihreät', expectedId: 5 },
  { query: 'keltaiset', expectedId: 6 },
  { query: 'oranssit', expectedId: 7 },
  { query: 'violetit', expectedId: 8 },
  { query: 'pinkit', expectedId: 9 },
  { query: 'harmaat', expectedId: 10 },
  { query: 'ruskeat', expectedId: 11 },
  { query: 'turkoosit', expectedId: 12 },
];

describe('runFuzzySearch color variants', () => {
  for (const c of cases) {
    it(`matches singular color from plural query: ${c.query}`, () => {
      const results = runFuzzySearch(c.query, baseUniversities);
      expect(results.map((r) => r.university.id)).toContain(c.expectedId);
    });
  }
});
